feat: maxlength
NaluKit/malio pull request #1
Opened 2023-04-09 16:16 UTC by philkohl

2023-04-09 17:07 UTC, FrankHossfeld requested changes

2023-04-09 17:07 UTC, FrankHossfeld commented on malio-processor/dependency-reduced-pom.xml
die kann raus ... :-D

2023-04-09 17:09 UTC, philkohl commented on malio-processor/dependency-reduced-pom.xml
die hab ich auch mal zur gitignore hinzugefügt, wurde jedoch schon einmal commitet. Muss ich gleich aus dem cache rauswerfen

2023-04-09 18:02 UTC, FrankHossfeld approved these changes

2023-04-10 07:37 UTC, FrankHossfeld commented on malio-processor/dependency-reduced-pom.xml
Oki Doki ... Passiert mir auch immer ... :-D

2023-04-11 10:06 UTC, merged